import streamlit as st
from fpdf import FPDF
from datetime import datetime

from utils.data_loader import load_data

st.set_page_config(
    page_title="Analysis Report",
    page_icon="📄",
    layout="wide"
)

st.title("📄 BioInsight AI Report")

try:
    # Load dataset
    expression_data = load_data()

    rows, cols = expression_data.shape
    avg_expression = expression_data.mean().mean()

    st.success("✅ Dataset Loaded Successfully")

    # -------------------------
    # Metrics
    # -------------------------
    col1, col2, col3 = st.columns(3)

    col1.metric("Genes", rows)
    col2.metric("Samples", cols)
    col3.metric("Average Expression", f"{avg_expression:.2f}")

    st.divider()

    st.subheader("📊 Summary Statistics")
    st.dataframe(expression_data.describe(), use_container_width=True)

    # -------------------------
    # Download CSV
    # -------------------------
    csv = expression_data.to_csv().encode("utf-8")

    st.download_button(
        label="⬇️ Download Cleaned Dataset (CSV)",
        data=csv,
        file_name="cleaned_gene_expression.csv",
        mime="text/csv"
    )

    st.divider()

    # -------------------------
    # PDF Report
    # -------------------------
    if st.button("📄 Generate PDF Report"):

        pdf = FPDF()
        pdf.add_page()

        pdf.set_font("Helvetica", "B", 18)
        pdf.cell(0, 12, "BioInsight AI Report", ln=True, align="C")

        pdf.ln(8)

        pdf.set_font("Helvetica", "", 12)

        pdf.cell(
            0,
            8,
            f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
            ln=True
        )

        pdf.ln(5)

        pdf.cell(0, 8, f"Number of Genes : {rows}", ln=True)
        pdf.cell(0, 8, f"Number of Samples : {cols}", ln=True)
        pdf.cell(0, 8, f"Average Expression : {avg_expression:.2f}", ln=True)

        pdf.ln(10)

        pdf.set_font("Helvetica", "B", 14)
        pdf.cell(0, 8, "Analysis Summary", ln=True)

        pdf.set_font("Helvetica", "", 12)

        summary = (
            "The gene expression dataset was successfully loaded, "
            "cleaned and analyzed using BioInsight AI.\n\n"
            "The dashboard includes:\n"
            "- Data Exploration\n"
            "- Interactive Visualizations\n"
            "- Machine Learning Analysis\n"
            "- Differential Gene Expression Analysis\n"
            "- Downloadable Reports\n\n"
            "This report was automatically generated by BioInsight AI."
        )

        pdf.multi_cell(0, 8, summary)

        pdf.output("BioInsight_Report.pdf")

        with open("BioInsight_Report.pdf", "rb") as pdf_file:

            st.success("✅ PDF Generated Successfully!")

            st.download_button(
                label="⬇️ Download PDF Report",
                data=pdf_file,
                file_name="BioInsight_Report.pdf",
                mime="application/pdf"
            )

except Exception as e:
    st.error(f"❌ Error: {e}")